---
title: "TC_MIMS_CF"
author: "CF"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
knitr::opts_knit$set(root.dir="~/GitHub/TownCreekWater/analyses/")
```

```{r load packages}
require("tidyverse")
require("ggpubr")
require("rstatix")
```

```{r Color-blind-friendly palette}
# From: http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/

cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```

```{r read in data}
SedSlurryFlux <- read.csv("../data/MIMS/Oct24/CalculatedSedSlurryFluxes.csv")

NetNratios <- read.csv("../data/MIMS/Oct24/NetNRatios.csv")
```

```{r}
SedSlurryFlux$axis_labels <- factor(x = c("In-stream \nupstream", "In-stream \nisland", "In-stream \ndownstream", "Dry \nupstream", "Dry \ndownstream"), levels = c("Dry \nupstream", "Dry \ndownstream", "In-stream \nupstream", "In-stream \ndownstream", "In-stream \nisland"))
```



```{r N barchart}
SedSlurryN.plot <- ggplot(data = SedSlurryFlux, aes(x=axis_labels, y=FinalFluxValue.umol.hr.m2._N)) +
  geom_bar(stat = "identity", position = position_dodge(), fill = "gray46", color = "gray46")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=30),axis.title=element_text(size=30,face="bold"),
          axis.text=element_text(size=30),  
          axis.title.y=element_text(margin=margin(r=10)),
          panel.border = element_rect(colour = "black",linetype=1),strip.text = element_text(size = 30), legend.position="right", legend.title = element_text(size=30), legend.text=element_text(size=30)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "", y = expression(paste("µmol N"[2],"-N m"^{-2}," hr"^{-1})), title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))+
  theme(axis.text.x = element_blank())

SedSlurryN.plot
```

```{r}
SedSlurryO2.plot <- ggplot(data = SedSlurryFlux, aes(x=axis_labels, y=FinalFluxValue.umol.hr.m2._O2)) +
  geom_bar(stat = "identity", position = position_dodge(), fill = "gray46", color = "gray46")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=30),axis.title=element_text(size=30,face="bold"),
          axis.text=element_text(size=30),  
          axis.title.y=element_text(margin=margin(r=10)),
          panel.border = element_rect(colour = "black",linetype=1),strip.text = element_text(size = 30), legend.position="right", legend.title = element_text(size=30), legend.text=element_text(size=30)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "", y = expression(paste("µmol O"[2]," m"^{-2}," hr"^{-1})), title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))

SedSlurryO2.plot
```

```{r panel}
# 2 panel figure, pre-post on the left, all groups on the right
MIMS_2panel.plot <- ggarrange(SedSlurryN.plot, SedSlurryO2.plot, ncol = 1, nrow = 2, legend = "none", align = "hv", labels = c("A", "B"))

MIMS_2panel.plot

#ggsave("../figures/MIMS_SedSlurry_2Panel.png", plot=MIMS_2panel.plot, device="png", path=NULL, scale=1, width=15, height=12, dpi=600, limitsize=TRUE, bg="white")
```

## Water column N2 saturation
```{r}
# test for extreme outliers:
Outliers <- NetNratios %>%
  identify_outliers(NetNratio)
Outliers
  # two outliers, but not extreme, so passes assumption.

# test normality:
NetNratios %>%
  shapiro_test(NetNratio)
  # Not normally distributed

  # QQ plot:
ggqqplot(NetNratios, "NetNratio")

# Not normal, so use Wilcoxon-Rank Sum test:
NetN_vs_1_Wilcox <- wilcox.test(NetNratios$NetNratio, alternative = "two.sided", mu = 1, paired = F, data = NetNratios)
  # maintain null hypothesis that NetN ratio = 1 (neither net denitrifying nor N-fixing)

# Subset for upstream:
NetN_vs_1_Wilcox_upstream <- wilcox.test(NetNratios$NetNratio, alternative = "two.sided", mu = 1, paired = F, data = NetNratios[1:9,])
  # maintain null hypothesis that NetN ratio = 1 (neither net denitrifying nor N-fixing)

# Subset for downstream:
NetN_vs_1_Wilcox_downstream <- wilcox.test(NetNratios$NetNratio, alternative = "two.sided", mu = 1, paired = F, data = NetNratios[10:18,])
  # maintain null hypothesis that NetN ratio = 1 (neither net denitrifying nor N-fixing)

# T tests:
NetN_vs_1_Ttest <- t_test(NetNratios, formula = NetNratio ~ 1, alternative = "two.sided", mu = 1)
NetN_vs_1_Ttest_up <- t_test(NetNratios[1:9,], formula = NetNratio ~ 1, alternative = "two.sided", mu = 1)
NetN_vs_1_Ttest_down <- t_test(NetNratios[10:18,], formula = NetNratio ~ 1, alternative = "two.sided", mu = 1)
NetN_vs_1_Ttest_down_drop_outliers <- t_test(NetNratios[10:16,], formula = NetNratio ~ 1, alternative = "two.sided", mu = 1)
```

```{r}
# Add short name column for X-axis:
NetNratios$shortID <- factor(c("I1", "I2", "I3", "I4", "I5", "I6", "I7", "I8", "I9", "D1", "D2", "D3", "D4", "D5", "D6", "D7", "D8", "D9"), levels = c(c("I1", "I2", "I3", "I4", "I5", "I6", "I7", "I8", "I9", "D1", "D2", "D3", "D4", "D5", "D6", "D7", "D8", "D9")))

NetNratios$Location <- as.factor(NetNratios$Location)
NetNratios$Location <- factor(NetNratios$Location, levels = c("upstream", "downstream"))

# Plus or minus one standard deviation limits:
y_mean <- mean(NetNratios$NetNratio)
y_sd <- sd(NetNratios$NetNratio)
y_limits <- c(y_mean - (3*y_sd), y_mean + (3*y_sd))
```



```{r}
NetNratios.plot <- ggplot(data = NetNratios, aes(x=shortID, y=NetNratio, color = Location, fill = Location, shape = Location)) +
  geom_point(size = 5)+
  scale_color_manual(values=c("#CC79A7","#0072B2"), labels = c("Upstream", "Downstream"), name="Sample Location") +
  scale_shape_manual(values = c(24, 25), labels = c("Upstream", "Downstream"), name = "Sample Location")+
  scale_fill_manual(values = c("#CC79A7","#0072B2"), labels = c("Upstream", "Downstream"), name="Sample Location")+
  annotate("rect", xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = 1.00, fill = "grey70", alpha = 0.25) +
  # Add shading above y = 1
  annotate("rect", xmin = -Inf, xmax = Inf, ymin = 1.00, ymax = Inf, fill = "grey1", alpha = 0.25) +
  geom_hline(yintercept = 1.00)+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=30),axis.title=element_text(size=30,face="bold"),
          axis.text=element_text(size=30),  
          axis.title.y=element_text(margin=margin(r=10)),
          panel.border = element_rect(colour = "black",linetype=1),strip.text = element_text(size = 30), legend.position="top", legend.title = element_text(size=30), legend.text=element_text(size=30)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "Sample", y = expression(paste("N"[2]," Saturation Ratio")), title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA), axis.text.x = element_text(angle=45, hjust = 1))+
  scale_y_continuous(limits = round(y_limits, digits = 2))
  #scale_y_continuous(limits = c(0.95, 1.05))
  #scale_y_continuous(limits = range(NetNratios$NetNratio))

NetNratios.plot

#ggsave("../figures/NetRatios.png", plot=NetNratios.plot, device="png", path=NULL, scale=1, width=11, height=8, dpi=600, limitsize=TRUE, bg="white")
```


