---
title: "TownCreekNitrate"
author: "CF"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r setup2}
# Clear environment:
rm(list=ls())

#use to set working directory 
knitr::opts_knit$set(root.dir="~/GitHub/TownCreekWater/analyses")
```

```{r packages}
require("tidyverse")
```


```{r read in data}
nitrate_up_down <- read.csv("../data/nitrate_up_down.csv")

nitrate_LONG <- read.csv("../data/nitrate_LongForm.csv")
```

```{r wrangle data}
# Make up or down a factor:
nitrate_LONG$Up_or_Down <- factor(nitrate_LONG$Up_or_Down, levels = c("Up", "Down"))

# Shorten date:

# Duplicate of nitrate_up_down for plotting:
nitrate_up_down2 <- nitrate_up_down
```

```{r Color-blind-friendly palette}
# From: http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/

cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```

```{r}
plot.nitrate <- ggplot() +
                     #geom_line(aes(shape=Up_or_Down, color=Up_or_Down, fill = Up_or_Down), size = 5) +
  geom_line(data = nitrate_up_down, aes(x=Date, y=NO3.Up, group=1))+
  geom_line(data = nitrate_up_down2, aes(x=Date, y=NO3.Down, group=2))+
  #scale_color_manual(values=c("#D55E00","#CC79A7"), labels = c("Upstream", "Downstream"), name="Sample Location") +
 # scale_shape_manual(values = c(24, 25), labels = c("Upstream", "Downstream"), name = "Sample Location")+
  #scale_fill_manual(values = c("#D55E00","#CC79A7"), labels = c("Upstream", "Downstream"), name="Sample Location")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=40),axis.title=element_text(size=40,face="bold"),
          axis.text=element_text(size=40),  
          axis.title.y=element_text(margin=margin(r=10)),
          axis.title.x = element_text(margin = margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 40), legend.position="none", legend.title = element_text(size=40), legend.text=element_text(size=40)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "Date", y = expression(paste("NO"[3]," mg/l")), title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))
  
 
plot.nitrate

#ggsave("../figures/denit_Summer_BigFont.png", plot=plot.denit_ACET_Summer_BigFont, device="png", path=NULL, scale=1, width=17, height=10, dpi=900, limitsize=TRUE, bg="white")
```



```{r plot nitrate data}
plot.nitrate_2 <- ggplot(nitrate_LONG, aes(x=as.Date(Date), y=NO3, color=Up_or_Down)) +
  geom_line(aes(x=Date, y=NO3, color=Up_or_Down, group=Up_or_Down))+
  geom_point(aes(x=Date, y=NO3, color=Up_or_Down, shape=Up_or_Down, fill=Up_or_Down))+
  scale_color_manual(values=c("#D55E00","#CC79A7"), labels = c("Upstream", "Downstream"), name="Sample Location") +
  scale_shape_manual(values = c(24, 25), labels = c("Upstream", "Downstream"), name = "Sample Location")+
  scale_fill_manual(values = c("#D55E00","#CC79A7"), labels = c("Upstream", "Downstream"), name="Sample Location")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=40),axis.title=element_text(size=40,face="bold"),
          axis.text=element_text(size=40),  
          axis.title.y=element_text(margin=margin(r=10)),
          axis.title.x = element_text(margin = margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 40), legend.position="right", legend.title = element_text(size=40), legend.text=element_text(size=40)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "Date", y = expression(paste("NO"[3]," mg/l")), title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))
  
 
plot.nitrate_2

#ggsave("../figures/denit_Summer_BigFont.png", plot=plot.denit_ACET_Summer_BigFont, device="png", path=NULL, scale=1, width=17, height=10, dpi=900, limitsize=TRUE, bg="white")
```

